
package com.soap.server;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MainDB", targetNamespace = "http://server.soap.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MainDB {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Integer>
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllUserIDsThatBoughtTheProduct", targetNamespace = "http://server.soap.com/", className = "com.soap.server.GetAllUserIDsThatBoughtTheProduct")
    @ResponseWrapper(localName = "getAllUserIDsThatBoughtTheProductResponse", targetNamespace = "http://server.soap.com/", className = "com.soap.server.GetAllUserIDsThatBoughtTheProductResponse")
    @Action(input = "http://server.soap.com/MainDB/getAllUserIDsThatBoughtTheProductRequest", output = "http://server.soap.com/MainDB/getAllUserIDsThatBoughtTheProductResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://server.soap.com/MainDB/getAllUserIDsThatBoughtTheProduct/Fault/DatabaseException")
    })
    public List<Integer> getAllUserIDsThatBoughtTheProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.soap.server.Pair>
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllStoresAndPricesBySpecificProduct", targetNamespace = "http://server.soap.com/", className = "com.soap.server.GetAllStoresAndPricesBySpecificProduct")
    @ResponseWrapper(localName = "getAllStoresAndPricesBySpecificProductResponse", targetNamespace = "http://server.soap.com/", className = "com.soap.server.GetAllStoresAndPricesBySpecificProductResponse")
    @Action(input = "http://server.soap.com/MainDB/getAllStoresAndPricesBySpecificProductRequest", output = "http://server.soap.com/MainDB/getAllStoresAndPricesBySpecificProductResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://server.soap.com/MainDB/getAllStoresAndPricesBySpecificProduct/Fault/DatabaseException")
    })
    public List<Pair> getAllStoresAndPricesBySpecificProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.soap.server.User
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://server.soap.com/", className = "com.soap.server.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://server.soap.com/", className = "com.soap.server.UpdateUserResponse")
    @Action(input = "http://server.soap.com/MainDB/updateUserRequest", output = "http://server.soap.com/MainDB/updateUserResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://server.soap.com/MainDB/updateUser/Fault/DatabaseException")
    })
    public User updateUser(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.soap.server.Product
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProductByID", targetNamespace = "http://server.soap.com/", className = "com.soap.server.GetProductByID")
    @ResponseWrapper(localName = "getProductByIDResponse", targetNamespace = "http://server.soap.com/", className = "com.soap.server.GetProductByIDResponse")
    @Action(input = "http://server.soap.com/MainDB/getProductByIDRequest", output = "http://server.soap.com/MainDB/getProductByIDResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://server.soap.com/MainDB/getProductByID/Fault/DatabaseException")
    })
    public Product getProductByID(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.soap.server.User
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserByID", targetNamespace = "http://server.soap.com/", className = "com.soap.server.GetUserByID")
    @ResponseWrapper(localName = "getUserByIDResponse", targetNamespace = "http://server.soap.com/", className = "com.soap.server.GetUserByIDResponse")
    @Action(input = "http://server.soap.com/MainDB/getUserByIDRequest", output = "http://server.soap.com/MainDB/getUserByIDResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://server.soap.com/MainDB/getUserByID/Fault/DatabaseException")
    })
    public User getUserByID(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.soap.server.Store
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateStore", targetNamespace = "http://server.soap.com/", className = "com.soap.server.UpdateStore")
    @ResponseWrapper(localName = "updateStoreResponse", targetNamespace = "http://server.soap.com/", className = "com.soap.server.UpdateStoreResponse")
    @Action(input = "http://server.soap.com/MainDB/updateStoreRequest", output = "http://server.soap.com/MainDB/updateStoreResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://server.soap.com/MainDB/updateStore/Fault/DatabaseException")
    })
    public Store updateStore(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteStore", targetNamespace = "http://server.soap.com/", className = "com.soap.server.DeleteStore")
    @ResponseWrapper(localName = "deleteStoreResponse", targetNamespace = "http://server.soap.com/", className = "com.soap.server.DeleteStoreResponse")
    @Action(input = "http://server.soap.com/MainDB/deleteStoreRequest", output = "http://server.soap.com/MainDB/deleteStoreResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://server.soap.com/MainDB/deleteStore/Fault/DatabaseException")
    })
    public void deleteStore(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.soap.server.Store
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStoreByID", targetNamespace = "http://server.soap.com/", className = "com.soap.server.GetStoreByID")
    @ResponseWrapper(localName = "getStoreByIDResponse", targetNamespace = "http://server.soap.com/", className = "com.soap.server.GetStoreByIDResponse")
    @Action(input = "http://server.soap.com/MainDB/getStoreByIDRequest", output = "http://server.soap.com/MainDB/getStoreByIDResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://server.soap.com/MainDB/getStoreByID/Fault/DatabaseException")
    })
    public Store getStoreByID(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.soap.server.Store
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addNewStore", targetNamespace = "http://server.soap.com/", className = "com.soap.server.AddNewStore")
    @ResponseWrapper(localName = "addNewStoreResponse", targetNamespace = "http://server.soap.com/", className = "com.soap.server.AddNewStoreResponse")
    @Action(input = "http://server.soap.com/MainDB/addNewStoreRequest", output = "http://server.soap.com/MainDB/addNewStoreResponse")
    public Store addNewStore(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteProduct", targetNamespace = "http://server.soap.com/", className = "com.soap.server.DeleteProduct")
    @ResponseWrapper(localName = "deleteProductResponse", targetNamespace = "http://server.soap.com/", className = "com.soap.server.DeleteProductResponse")
    @Action(input = "http://server.soap.com/MainDB/deleteProductRequest", output = "http://server.soap.com/MainDB/deleteProductResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://server.soap.com/MainDB/deleteProduct/Fault/DatabaseException")
    })
    public void deleteProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteUser", targetNamespace = "http://server.soap.com/", className = "com.soap.server.DeleteUser")
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://server.soap.com/", className = "com.soap.server.DeleteUserResponse")
    @Action(input = "http://server.soap.com/MainDB/deleteUserRequest", output = "http://server.soap.com/MainDB/deleteUserResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://server.soap.com/MainDB/deleteUser/Fault/DatabaseException")
    })
    public void deleteUser(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.soap.server.Product
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addNewProduct", targetNamespace = "http://server.soap.com/", className = "com.soap.server.AddNewProduct")
    @ResponseWrapper(localName = "addNewProductResponse", targetNamespace = "http://server.soap.com/", className = "com.soap.server.AddNewProductResponse")
    @Action(input = "http://server.soap.com/MainDB/addNewProductRequest", output = "http://server.soap.com/MainDB/addNewProductResponse")
    public Product addNewProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.soap.server.Product
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateProduct", targetNamespace = "http://server.soap.com/", className = "com.soap.server.UpdateProduct")
    @ResponseWrapper(localName = "updateProductResponse", targetNamespace = "http://server.soap.com/", className = "com.soap.server.UpdateProductResponse")
    @Action(input = "http://server.soap.com/MainDB/updateProductRequest", output = "http://server.soap.com/MainDB/updateProductResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://server.soap.com/MainDB/updateProduct/Fault/DatabaseException")
    })
    public Product updateProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.soap.server.Product>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllProducts", targetNamespace = "http://server.soap.com/", className = "com.soap.server.GetAllProducts")
    @ResponseWrapper(localName = "getAllProductsResponse", targetNamespace = "http://server.soap.com/", className = "com.soap.server.GetAllProductsResponse")
    @Action(input = "http://server.soap.com/MainDB/getAllProductsRequest", output = "http://server.soap.com/MainDB/getAllProductsResponse")
    public List<Product> getAllProducts();

    /**
     * 
     * @return
     *     returns java.util.List<com.soap.server.Store>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllStores", targetNamespace = "http://server.soap.com/", className = "com.soap.server.GetAllStores")
    @ResponseWrapper(localName = "getAllStoresResponse", targetNamespace = "http://server.soap.com/", className = "com.soap.server.GetAllStoresResponse")
    @Action(input = "http://server.soap.com/MainDB/getAllStoresRequest", output = "http://server.soap.com/MainDB/getAllStoresResponse")
    public List<Store> getAllStores();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.soap.server.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addNewUser", targetNamespace = "http://server.soap.com/", className = "com.soap.server.AddNewUser")
    @ResponseWrapper(localName = "addNewUserResponse", targetNamespace = "http://server.soap.com/", className = "com.soap.server.AddNewUserResponse")
    @Action(input = "http://server.soap.com/MainDB/addNewUserRequest", output = "http://server.soap.com/MainDB/addNewUserResponse")
    public User addNewUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "addToCart", targetNamespace = "http://server.soap.com/", className = "com.soap.server.AddToCart")
    @ResponseWrapper(localName = "addToCartResponse", targetNamespace = "http://server.soap.com/", className = "com.soap.server.AddToCartResponse")
    @Action(input = "http://server.soap.com/MainDB/addToCartRequest", output = "http://server.soap.com/MainDB/addToCartResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://server.soap.com/MainDB/addToCart/Fault/DatabaseException")
    })
    public void addToCart(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteFromCart", targetNamespace = "http://server.soap.com/", className = "com.soap.server.DeleteFromCart")
    @ResponseWrapper(localName = "deleteFromCartResponse", targetNamespace = "http://server.soap.com/", className = "com.soap.server.DeleteFromCartResponse")
    @Action(input = "http://server.soap.com/MainDB/deleteFromCartRequest", output = "http://server.soap.com/MainDB/deleteFromCartResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://server.soap.com/MainDB/deleteFromCart/Fault/DatabaseException")
    })
    public void deleteFromCart(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "payForUserCart", targetNamespace = "http://server.soap.com/", className = "com.soap.server.PayForUserCart")
    @ResponseWrapper(localName = "payForUserCartResponse", targetNamespace = "http://server.soap.com/", className = "com.soap.server.PayForUserCartResponse")
    @Action(input = "http://server.soap.com/MainDB/payForUserCartRequest", output = "http://server.soap.com/MainDB/payForUserCartResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://server.soap.com/MainDB/payForUserCart/Fault/DatabaseException")
    })
    public int payForUserCart(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.soap.server.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllUsers", targetNamespace = "http://server.soap.com/", className = "com.soap.server.GetAllUsers")
    @ResponseWrapper(localName = "getAllUsersResponse", targetNamespace = "http://server.soap.com/", className = "com.soap.server.GetAllUsersResponse")
    @Action(input = "http://server.soap.com/MainDB/getAllUsersRequest", output = "http://server.soap.com/MainDB/getAllUsersResponse")
    public List<User> getAllUsers();

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.soap.server.CustomerReview
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addNewCustomerReview", targetNamespace = "http://server.soap.com/", className = "com.soap.server.AddNewCustomerReview")
    @ResponseWrapper(localName = "addNewCustomerReviewResponse", targetNamespace = "http://server.soap.com/", className = "com.soap.server.AddNewCustomerReviewResponse")
    @Action(input = "http://server.soap.com/MainDB/addNewCustomerReviewRequest", output = "http://server.soap.com/MainDB/addNewCustomerReviewResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://server.soap.com/MainDB/addNewCustomerReview/Fault/DatabaseException")
    })
    public CustomerReview addNewCustomerReview(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.soap.server.CustomerReview
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCustomerReviewByID", targetNamespace = "http://server.soap.com/", className = "com.soap.server.GetCustomerReviewByID")
    @ResponseWrapper(localName = "getCustomerReviewByIDResponse", targetNamespace = "http://server.soap.com/", className = "com.soap.server.GetCustomerReviewByIDResponse")
    @Action(input = "http://server.soap.com/MainDB/getCustomerReviewByIDRequest", output = "http://server.soap.com/MainDB/getCustomerReviewByIDResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://server.soap.com/MainDB/getCustomerReviewByID/Fault/DatabaseException")
    })
    public CustomerReview getCustomerReviewByID(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.soap.server.CustomerReview
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateCustomerReview", targetNamespace = "http://server.soap.com/", className = "com.soap.server.UpdateCustomerReview")
    @ResponseWrapper(localName = "updateCustomerReviewResponse", targetNamespace = "http://server.soap.com/", className = "com.soap.server.UpdateCustomerReviewResponse")
    @Action(input = "http://server.soap.com/MainDB/updateCustomerReviewRequest", output = "http://server.soap.com/MainDB/updateCustomerReviewResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://server.soap.com/MainDB/updateCustomerReview/Fault/DatabaseException")
    })
    public CustomerReview updateCustomerReview(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteCustomerReview", targetNamespace = "http://server.soap.com/", className = "com.soap.server.DeleteCustomerReview")
    @ResponseWrapper(localName = "deleteCustomerReviewResponse", targetNamespace = "http://server.soap.com/", className = "com.soap.server.DeleteCustomerReviewResponse")
    @Action(input = "http://server.soap.com/MainDB/deleteCustomerReviewRequest", output = "http://server.soap.com/MainDB/deleteCustomerReviewResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://server.soap.com/MainDB/deleteCustomerReview/Fault/DatabaseException")
    })
    public void deleteCustomerReview(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.soap.server.Product>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllProductsByCategory", targetNamespace = "http://server.soap.com/", className = "com.soap.server.GetAllProductsByCategory")
    @ResponseWrapper(localName = "getAllProductsByCategoryResponse", targetNamespace = "http://server.soap.com/", className = "com.soap.server.GetAllProductsByCategoryResponse")
    @Action(input = "http://server.soap.com/MainDB/getAllProductsByCategoryRequest", output = "http://server.soap.com/MainDB/getAllProductsByCategoryResponse")
    public List<Product> getAllProductsByCategory(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAverageRatingOfProduct", targetNamespace = "http://server.soap.com/", className = "com.soap.server.GetAverageRatingOfProduct")
    @ResponseWrapper(localName = "getAverageRatingOfProductResponse", targetNamespace = "http://server.soap.com/", className = "com.soap.server.GetAverageRatingOfProductResponse")
    @Action(input = "http://server.soap.com/MainDB/getAverageRatingOfProductRequest", output = "http://server.soap.com/MainDB/getAverageRatingOfProductResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://server.soap.com/MainDB/getAverageRatingOfProduct/Fault/DatabaseException")
    })
    public double getAverageRatingOfProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.soap.server.CustomerReview>
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllCustomerReviews", targetNamespace = "http://server.soap.com/", className = "com.soap.server.GetAllCustomerReviews")
    @ResponseWrapper(localName = "getAllCustomerReviewsResponse", targetNamespace = "http://server.soap.com/", className = "com.soap.server.GetAllCustomerReviewsResponse")
    @Action(input = "http://server.soap.com/MainDB/getAllCustomerReviewsRequest", output = "http://server.soap.com/MainDB/getAllCustomerReviewsResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://server.soap.com/MainDB/getAllCustomerReviews/Fault/DatabaseException")
    })
    public List<CustomerReview> getAllCustomerReviews(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.soap.server.Pair>
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllProductsAndPricesInStore", targetNamespace = "http://server.soap.com/", className = "com.soap.server.GetAllProductsAndPricesInStore")
    @ResponseWrapper(localName = "getAllProductsAndPricesInStoreResponse", targetNamespace = "http://server.soap.com/", className = "com.soap.server.GetAllProductsAndPricesInStoreResponse")
    @Action(input = "http://server.soap.com/MainDB/getAllProductsAndPricesInStoreRequest", output = "http://server.soap.com/MainDB/getAllProductsAndPricesInStoreResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://server.soap.com/MainDB/getAllProductsAndPricesInStore/Fault/DatabaseException")
    })
    public List<Pair> getAllProductsAndPricesInStore(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.soap.server.Pair>
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProductIDsAndStoreIDsBought", targetNamespace = "http://server.soap.com/", className = "com.soap.server.GetProductIDsAndStoreIDsBought")
    @ResponseWrapper(localName = "getProductIDsAndStoreIDsBoughtResponse", targetNamespace = "http://server.soap.com/", className = "com.soap.server.GetProductIDsAndStoreIDsBoughtResponse")
    @Action(input = "http://server.soap.com/MainDB/getProductIDsAndStoreIDsBoughtRequest", output = "http://server.soap.com/MainDB/getProductIDsAndStoreIDsBoughtResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://server.soap.com/MainDB/getProductIDsAndStoreIDsBought/Fault/DatabaseException")
    })
    public List<Pair> getProductIDsAndStoreIDsBought(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.soap.server.Pair>
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProductIDsAndStoreIDsFromCart", targetNamespace = "http://server.soap.com/", className = "com.soap.server.GetProductIDsAndStoreIDsFromCart")
    @ResponseWrapper(localName = "getProductIDsAndStoreIDsFromCartResponse", targetNamespace = "http://server.soap.com/", className = "com.soap.server.GetProductIDsAndStoreIDsFromCartResponse")
    @Action(input = "http://server.soap.com/MainDB/getProductIDsAndStoreIDsFromCartRequest", output = "http://server.soap.com/MainDB/getProductIDsAndStoreIDsFromCartResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://server.soap.com/MainDB/getProductIDsAndStoreIDsFromCart/Fault/DatabaseException")
    })
    public List<Pair> getProductIDsAndStoreIDsFromCart(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws DatabaseException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "linkStoreAndProduct", targetNamespace = "http://server.soap.com/", className = "com.soap.server.LinkStoreAndProduct")
    @ResponseWrapper(localName = "linkStoreAndProductResponse", targetNamespace = "http://server.soap.com/", className = "com.soap.server.LinkStoreAndProductResponse")
    @Action(input = "http://server.soap.com/MainDB/linkStoreAndProductRequest", output = "http://server.soap.com/MainDB/linkStoreAndProductResponse", fault = {
        @FaultAction(className = DatabaseException_Exception.class, value = "http://server.soap.com/MainDB/linkStoreAndProduct/Fault/DatabaseException")
    })
    public void linkStoreAndProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2)
        throws DatabaseException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.soap.server.Product>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllProductsByMaxPrice", targetNamespace = "http://server.soap.com/", className = "com.soap.server.GetAllProductsByMaxPrice")
    @ResponseWrapper(localName = "getAllProductsByMaxPriceResponse", targetNamespace = "http://server.soap.com/", className = "com.soap.server.GetAllProductsByMaxPriceResponse")
    @Action(input = "http://server.soap.com/MainDB/getAllProductsByMaxPriceRequest", output = "http://server.soap.com/MainDB/getAllProductsByMaxPriceResponse")
    public List<Product> getAllProductsByMaxPrice(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
