
package com.soap.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MainDBService", targetNamespace = "http://server.soap.com/", wsdlLocation = "http://ron-laptop:8080/DS_EX1_SOAP_Server/MainDBService?wsdl")
public class MainDBService
    extends Service
{

    private final static URL MAINDBSERVICE_WSDL_LOCATION;
    private final static WebServiceException MAINDBSERVICE_EXCEPTION;
    private final static QName MAINDBSERVICE_QNAME = new QName("http://server.soap.com/", "MainDBService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://ron-laptop:8080/DS_EX1_SOAP_Server/MainDBService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MAINDBSERVICE_WSDL_LOCATION = url;
        MAINDBSERVICE_EXCEPTION = e;
    }

    public MainDBService() {
        super(__getWsdlLocation(), MAINDBSERVICE_QNAME);
    }

    public MainDBService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MAINDBSERVICE_QNAME, features);
    }

    public MainDBService(URL wsdlLocation) {
        super(wsdlLocation, MAINDBSERVICE_QNAME);
    }

    public MainDBService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MAINDBSERVICE_QNAME, features);
    }

    public MainDBService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MainDBService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MainDB
     */
    @WebEndpoint(name = "MainDBPort")
    public MainDB getMainDBPort() {
        return super.getPort(new QName("http://server.soap.com/", "MainDBPort"), MainDB.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MainDB
     */
    @WebEndpoint(name = "MainDBPort")
    public MainDB getMainDBPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.soap.com/", "MainDBPort"), MainDB.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MAINDBSERVICE_EXCEPTION!= null) {
            throw MAINDBSERVICE_EXCEPTION;
        }
        return MAINDBSERVICE_WSDL_LOCATION;
    }

}
